version: '3.9'

services:
  http-service:
    image: ghcr.io/connormolz/espwebservice:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db:5432
      - DB_USER=user
      - DB_PASSWORD=test
      - DB_NAME=smart_home
    links:
      - "db:db"

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ""
      POSTGRES_USER: "user"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-db-volume:/var/lib/postgresql


volumes:
  postgres-db-volume:
    name: postgres-db-volume
